/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/bin/commands/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 1
#endif
#define TCC_VERSION "0.9.28rc"

#define TCC_VERSION_A 0
#define TCC_VERSION_B 9
#define TCC_VERSION_C 28

#define GCC_MAJOR 11
#define GCC_MINOR 4
#define CC_NAME CC_gcc
